CREATE TABLE IF NOT EXISTS "public"."prompts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" "uuid" NOT NULL,
    "type" "public"."prompt_type" DEFAULT 'chat'::"public"."prompt_type" NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS prompts_pkey ON "public"."prompts" USING btree (id);

ALTER TABLE "public"."prompts" ADD CONSTRAINT "prompts_pkey" PRIMARY KEY USING INDEX "prompts_pkey";

-- No FK into auth.users: see supabase/migrations/20260801000000_remove_auth.sql.

-- RLS intentionally disabled: the policy was keyed on auth.uid().
ALTER TABLE "public"."prompts" DISABLE ROW LEVEL SECURITY;
