/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as AssetsSplatRouteImport } from './routes/assets.$'
import { Route as ApiTitleGeneratorRouteImport } from './routes/api/title-generator'
import { Route as ApiPublicAssetRouteImport } from './routes/api/public-asset'
import { Route as ApiPromptGeneratorRouteImport } from './routes/api/prompt-generator'
import { Route as ApiParametricChatRouteImport } from './routes/api/parametric-chat'
import { Route as ApiMeshRouteImport } from './routes/api/mesh'
import { Route as ApiForkConversationRouteImport } from './routes/api/fork-conversation'
import { Route as ApiFalWebhookRouteImport } from './routes/api/fal-webhook'
import { Route as ApiCreativeChatRouteImport } from './routes/api/creative-chat'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing-status'
import { Route as ApiBillingProductsRouteImport } from './routes/api/billing-products'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing-checkout'
import { Route as ApiAvailableModelsRouteImport } from './routes/api/available-models'
import { Route as LayoutSubscriptionRouteImport } from './routes/_layout/subscription'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutSplatRouteImport } from './routes/_layout/$'
import { Route as ApiJacksonPollockSplatRouteImport } from './routes/api/jackson-pollock/$'
import { Route as LayoutEditorIdRouteImport } from './routes/_layout/editor/$id'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTitleGeneratorRoute = ApiTitleGeneratorRouteImport.update({
  id: '/api/title-generator',
  path: '/api/title-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssetRoute = ApiPublicAssetRouteImport.update({
  id: '/api/public-asset',
  path: '/api/public-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptGeneratorRoute = ApiPromptGeneratorRouteImport.update({
  id: '/api/prompt-generator',
  path: '/api/prompt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParametricChatRoute = ApiParametricChatRouteImport.update({
  id: '/api/parametric-chat',
  path: '/api/parametric-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeshRoute = ApiMeshRouteImport.update({
  id: '/api/mesh',
  path: '/api/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForkConversationRoute = ApiForkConversationRouteImport.update({
  id: '/api/fork-conversation',
  path: '/api/fork-conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFalWebhookRoute = ApiFalWebhookRouteImport.update({
  id: '/api/fal-webhook',
  path: '/api/fal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreativeChatRoute = ApiCreativeChatRouteImport.update({
  id: '/api/creative-chat',
  path: '/api/creative-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing-status',
  path: '/api/billing-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingProductsRoute = ApiBillingProductsRouteImport.update({
  id: '/api/billing-products',
  path: '/api/billing-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing-checkout',
  path: '/api/billing-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvailableModelsRoute = ApiAvailableModelsRouteImport.update({
  id: '/api/available-models',
  path: '/api/available-models',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSubscriptionRoute = LayoutSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSplatRoute = LayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiJacksonPollockSplatRoute = ApiJacksonPollockSplatRouteImport.update({
  id: '/api/jackson-pollock/$',
  path: '/api/jackson-pollock/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutEditorIdRoute = LayoutEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$': typeof LayoutSplatRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/subscription': typeof LayoutSubscriptionRoute
  '/api/available-models': typeof ApiAvailableModelsRoute
  '/api/billing-checkout': typeof ApiBillingCheckoutRoute
  '/api/billing-products': typeof ApiBillingProductsRoute
  '/api/billing-status': typeof ApiBillingStatusRoute
  '/api/creative-chat': typeof ApiCreativeChatRoute
  '/api/fal-webhook': typeof ApiFalWebhookRoute
  '/api/fork-conversation': typeof ApiForkConversationRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/parametric-chat': typeof ApiParametricChatRoute
  '/api/prompt-generator': typeof ApiPromptGeneratorRoute
  '/api/public-asset': typeof ApiPublicAssetRoute
  '/api/title-generator': typeof ApiTitleGeneratorRoute
  '/assets/$': typeof AssetsSplatRoute
  '/share/$id': typeof ShareIdRoute
  '/editor/$id': typeof LayoutEditorIdRoute
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$': typeof LayoutSplatRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/subscription': typeof LayoutSubscriptionRoute
  '/api/available-models': typeof ApiAvailableModelsRoute
  '/api/billing-checkout': typeof ApiBillingCheckoutRoute
  '/api/billing-products': typeof ApiBillingProductsRoute
  '/api/billing-status': typeof ApiBillingStatusRoute
  '/api/creative-chat': typeof ApiCreativeChatRoute
  '/api/fal-webhook': typeof ApiFalWebhookRoute
  '/api/fork-conversation': typeof ApiForkConversationRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/parametric-chat': typeof ApiParametricChatRoute
  '/api/prompt-generator': typeof ApiPromptGeneratorRoute
  '/api/public-asset': typeof ApiPublicAssetRoute
  '/api/title-generator': typeof ApiTitleGeneratorRoute
  '/assets/$': typeof AssetsSplatRoute
  '/share/$id': typeof ShareIdRoute
  '/': typeof LayoutIndexRoute
  '/editor/$id': typeof LayoutEditorIdRoute
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_layout/$': typeof LayoutSplatRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/subscription': typeof LayoutSubscriptionRoute
  '/api/available-models': typeof ApiAvailableModelsRoute
  '/api/billing-checkout': typeof ApiBillingCheckoutRoute
  '/api/billing-products': typeof ApiBillingProductsRoute
  '/api/billing-status': typeof ApiBillingStatusRoute
  '/api/creative-chat': typeof ApiCreativeChatRoute
  '/api/fal-webhook': typeof ApiFalWebhookRoute
  '/api/fork-conversation': typeof ApiForkConversationRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/parametric-chat': typeof ApiParametricChatRoute
  '/api/prompt-generator': typeof ApiPromptGeneratorRoute
  '/api/public-asset': typeof ApiPublicAssetRoute
  '/api/title-generator': typeof ApiTitleGeneratorRoute
  '/assets/$': typeof AssetsSplatRoute
  '/share/$id': typeof ShareIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/editor/$id': typeof LayoutEditorIdRoute
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/$'
    | '/history'
    | '/settings'
    | '/subscription'
    | '/api/available-models'
    | '/api/billing-checkout'
    | '/api/billing-products'
    | '/api/billing-status'
    | '/api/creative-chat'
    | '/api/fal-webhook'
    | '/api/fork-conversation'
    | '/api/mesh'
    | '/api/parametric-chat'
    | '/api/prompt-generator'
    | '/api/public-asset'
    | '/api/title-generator'
    | '/assets/$'
    | '/share/$id'
    | '/editor/$id'
    | '/api/jackson-pollock/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/$'
    | '/history'
    | '/settings'
    | '/subscription'
    | '/api/available-models'
    | '/api/billing-checkout'
    | '/api/billing-products'
    | '/api/billing-status'
    | '/api/creative-chat'
    | '/api/fal-webhook'
    | '/api/fork-conversation'
    | '/api/mesh'
    | '/api/parametric-chat'
    | '/api/prompt-generator'
    | '/api/public-asset'
    | '/api/title-generator'
    | '/assets/$'
    | '/share/$id'
    | '/'
    | '/editor/$id'
    | '/api/jackson-pollock/$'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/_layout/$'
    | '/_layout/history'
    | '/_layout/settings'
    | '/_layout/subscription'
    | '/api/available-models'
    | '/api/billing-checkout'
    | '/api/billing-products'
    | '/api/billing-status'
    | '/api/creative-chat'
    | '/api/fal-webhook'
    | '/api/fork-conversation'
    | '/api/mesh'
    | '/api/parametric-chat'
    | '/api/prompt-generator'
    | '/api/public-asset'
    | '/api/title-generator'
    | '/assets/$'
    | '/share/$id'
    | '/_layout/'
    | '/_layout/editor/$id'
    | '/api/jackson-pollock/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiAvailableModelsRoute: typeof ApiAvailableModelsRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingProductsRoute: typeof ApiBillingProductsRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiCreativeChatRoute: typeof ApiCreativeChatRoute
  ApiFalWebhookRoute: typeof ApiFalWebhookRoute
  ApiForkConversationRoute: typeof ApiForkConversationRoute
  ApiMeshRoute: typeof ApiMeshRoute
  ApiParametricChatRoute: typeof ApiParametricChatRoute
  ApiPromptGeneratorRoute: typeof ApiPromptGeneratorRoute
  ApiPublicAssetRoute: typeof ApiPublicAssetRoute
  ApiTitleGeneratorRoute: typeof ApiTitleGeneratorRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  ShareIdRoute: typeof ShareIdRoute
  ApiJacksonPollockSplatRoute: typeof ApiJacksonPollockSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/title-generator': {
      id: '/api/title-generator'
      path: '/api/title-generator'
      fullPath: '/api/title-generator'
      preLoaderRoute: typeof ApiTitleGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-asset': {
      id: '/api/public-asset'
      path: '/api/public-asset'
      fullPath: '/api/public-asset'
      preLoaderRoute: typeof ApiPublicAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-generator': {
      id: '/api/prompt-generator'
      path: '/api/prompt-generator'
      fullPath: '/api/prompt-generator'
      preLoaderRoute: typeof ApiPromptGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parametric-chat': {
      id: '/api/parametric-chat'
      path: '/api/parametric-chat'
      fullPath: '/api/parametric-chat'
      preLoaderRoute: typeof ApiParametricChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesh': {
      id: '/api/mesh'
      path: '/api/mesh'
      fullPath: '/api/mesh'
      preLoaderRoute: typeof ApiMeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fork-conversation': {
      id: '/api/fork-conversation'
      path: '/api/fork-conversation'
      fullPath: '/api/fork-conversation'
      preLoaderRoute: typeof ApiForkConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fal-webhook': {
      id: '/api/fal-webhook'
      path: '/api/fal-webhook'
      fullPath: '/api/fal-webhook'
      preLoaderRoute: typeof ApiFalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creative-chat': {
      id: '/api/creative-chat'
      path: '/api/creative-chat'
      fullPath: '/api/creative-chat'
      preLoaderRoute: typeof ApiCreativeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing-status': {
      id: '/api/billing-status'
      path: '/api/billing-status'
      fullPath: '/api/billing-status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing-products': {
      id: '/api/billing-products'
      path: '/api/billing-products'
      fullPath: '/api/billing-products'
      preLoaderRoute: typeof ApiBillingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing-checkout': {
      id: '/api/billing-checkout'
      path: '/api/billing-checkout'
      fullPath: '/api/billing-checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/available-models': {
      id: '/api/available-models'
      path: '/api/available-models'
      fullPath: '/api/available-models'
      preLoaderRoute: typeof ApiAvailableModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/subscription': {
      id: '/_layout/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof LayoutSubscriptionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$': {
      id: '/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof LayoutSplatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/jackson-pollock/$': {
      id: '/api/jackson-pollock/$'
      path: '/api/jackson-pollock/$'
      fullPath: '/api/jackson-pollock/$'
      preLoaderRoute: typeof ApiJacksonPollockSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/editor/$id': {
      id: '/_layout/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof LayoutEditorIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSplatRoute: typeof LayoutSplatRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSubscriptionRoute: typeof LayoutSubscriptionRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEditorIdRoute: typeof LayoutEditorIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSplatRoute: LayoutSplatRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSubscriptionRoute: LayoutSubscriptionRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEditorIdRoute: LayoutEditorIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiAvailableModelsRoute: ApiAvailableModelsRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingProductsRoute: ApiBillingProductsRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiCreativeChatRoute: ApiCreativeChatRoute,
  ApiFalWebhookRoute: ApiFalWebhookRoute,
  ApiForkConversationRoute: ApiForkConversationRoute,
  ApiMeshRoute: ApiMeshRoute,
  ApiParametricChatRoute: ApiParametricChatRoute,
  ApiPromptGeneratorRoute: ApiPromptGeneratorRoute,
  ApiPublicAssetRoute: ApiPublicAssetRoute,
  ApiTitleGeneratorRoute: ApiTitleGeneratorRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  ShareIdRoute: ShareIdRoute,
  ApiJacksonPollockSplatRoute: ApiJacksonPollockSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
